<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="sathvik" name="Way2SMSModule.SendSMSTest" tests="4" failures="1" timestamp="27 Sep 2018 11:29:21 GMT" time="68.315" errors="0">
  <testcase name="launch" time="8.586" classname="Way2SMSModule.SendSMSTest"/>
  <testcase name="login" time="3.941" classname="Way2SMSModule.SendSMSTest"/>
  <testcase name="sendMessage" time="54.775" classname="Way2SMSModule.SendSMSTest">
    <failure type="java.lang.AssertionError" message="Way2SMS Login Test was Interrupted expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Way2SMS Login Test was Interrupted expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at Way2SMSModule.SendSMSTest.sendMessage(SendSMSTest.java:59)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- sendMessage -->
  <testcase name="close" time="1.013" classname="Way2SMSModule.SendSMSTest"/>
</testsuite> <!-- Way2SMSModule.SendSMSTest -->
